# Site settings
# in the templates available like {{ site.myvariable }}.
title: Anurag Singh
email: anurag.singh@columbia.edu
brand: Anurag Singh
headline: Phd Candidate &middot; Economics Department &middot; Columbia University
description: > # this means to ignore newlines until "baseurl:"
 Anurag Singh &middot; Economics Department &middot; Columbia University
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://s-anurag.github.io/" # the base hostname & protocol for your site
copyright: Anurag Singh

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: anurag.singh@columbia.edu
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

